strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.x'

- script: |
    npm install lix

    npx lix download

    npx haxe test.hxml -D reporter=test.XUnit2Reporter -D report-name=Test-Results
  displayName: Run Tests
  env:
    AGENT_OS: $(Agent.OS)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: Test-Results.xml
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: $(Agent.OS) Tests
    buildPlatform: $(Agent.OS)
    failTaskOnFailedTests: true
  env:
    AGENT_OS: $(Agent.OS)
